Don't prime calypso.live for external PR authors

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -473,7 +473,12 @@ jobs:
       - prepare
       - run:
           name: Prime calypso.live build
-          command: ./test/e2e/scripts/wait-for-running-branch.sh
+          command: |
+            if [[ ! -z $CIRCLE_PR_USERNAME ]]; then
+              ./test/e2e/scripts/wait-for-running-branch.sh
+            fi
+            echo 'PRs from external authors cannot run on calypso.live'
+            exit 1
 
   test-e2e:
     <<: *defaults
