CI: Add ICFY failure notification (#28403)
* Add ICFY failed build notification

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -378,6 +378,26 @@ jobs:
       - save_cache: *save-babel-client-cache
       - store-artifacts-and-test-results
       - run:
+          name: Notify ICFY of failed build
+          when: on_fail
+          command: |
+            #
+            # This block should not cause a test failure and block PRs.
+            # The shell should never error and exit 0 to indicate success.
+            #
+            set +o errexit
+            curl -X POST                                                                     \
+              "http://api.iscalypsofastyet.com:5000/submit-stats-failed?secret=$ICFY_SECRET" \
+              -H 'Cache-Control: no-cache'                                                   \
+              -H 'Content-Type: application/json'                                            \
+              -d '{
+                    "payload": {
+                      "branch": "'"$CIRCLE_BRANCH"'",
+                      "build_num": '"$CIRCLE_BUILD_NUM"',
+                      "sha": "'"$CIRCLE_SHA1"'"
+                    }
+                  }'
+      - run:
           name: Notify ICFY
           command: |
             #
@@ -387,8 +407,7 @@ jobs:
             set +o errexit
             if [ -e "$CIRCLE_ARTIFACTS/icfy/stats.json" ] && [ -e "$CIRCLE_ARTIFACTS/icfy/chart.json" ]; then
               ANCESTOR_SHA1=$(git merge-base HEAD origin/master)
-              curl                                                                      \
-                -X POST                                                                 \
+              curl -X POST                                                              \
                 "http://api.iscalypsofastyet.com:5000/submit-stats?secret=$ICFY_SECRET" \
                 -H 'Cache-Control: no-cache'                                            \
                 -H 'Content-Type: application/json'                                     \
